feature/modal html/css markup
rafallakomiec/filmoteka-goit-js-group-project pull request #3
Opened 2023-04-15 09:57 UTC by OstTomasz

Stworzony markup modala:
- na razie wszystko jest "na sztywno", jak będzie pod co podpiąć, to wtedy będzie zabawa ;)
- na razie przybrałem przykładowe wartości, żeby jakkolwiek to wyglądało
- makieta stworzona na szybko, potem będę ją doprowadzał do porządanego wyglądu :)

W icons.svg podzieliłem ciąg na linie, żeby łatwiej się pracowało!

2023-04-18 17:29 UTC, mkubera requested changes
przeksztalc na modul

2023-04-18 17:29 UTC, mkubera commented on src/js/modules/openMovieModal.js
> +// import { fetchItems } from './fetchItems';
dead code

2023-04-18 17:29 UTC, mkubera commented on src/js/modules/openMovieModal.js
> +  const refs = {
to tworzy glob zmienna (BAD).
Przepisz kod (samo-wyw sie funkcje) na ES6 MODULE (import/export).

2023-04-18 17:29 UTC, mkubera commented on src/js/modules/openMovieModal.js
> +    openModalBtn: document.querySelector('[data-modal-open]'),
zastap `document.querySelector` funkcj pomocnicza `const qs = (s) => document.querySelector(s);`

2023-04-18 17:29 UTC, mkubera commented on src/js/modules/openMovieModal.js
> +  }
zrob z tego funkcje strzalkowa :)

2023-04-18 17:29 UTC, mkubera commented on src/sass/partials/_movie-modal.scss
> -// PLEASE USE BEM METHODOLOGY
przenies informacje do README

2023-04-19 14:12 UTC, rafallakomiec approved these changes
Acceptable after leader fixes.
Take care of JS in separate branch!
Read Mikołaj Kubera code review here for tips, and PMs.

2023-04-19 14:16 UTC, merged